name = "graphplan"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Graphplan"]

[leanOptions]
pp.unicode.fun = true                 # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "Regex"
git = "https://github.com/pandaman64/lean-regex"
rev = "v4.24.0"
subDir = "regex"

[[lean_lib]]
name = "Graphplan"

[[lean_exe]]
name = "debug"
root = "Graphplan"

[[lean_exe]]
name = "Hanoi-test"
root = "examples.Hanoi"

[[lean_exe]]
name = "Rocket-test"
root = "examples.RocketN"
